name: milk_ride_live_wc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  dio: ^5.8.0+1
  loader_overlay: ^5.0.0
  build_runner: ^2.4.15
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  retrofit_generator: ^9.1.9
  fpdart: ^1.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  pinput: ^5.0.1
  otp_timer_button: ^1.1.1
  smooth_page_indicator: ^1.2.1
  get_storage: ^2.1.1
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.0
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.3
  shimmer: ^3.0.0
  intl: 0.19.0
  easy_date_timeline: ^2.0.9
  flutter_launcher_icons: ^0.14.3
  sms_autofill: ^2.4.1
  razorpay_flutter: ^1.4.0
  clipboard: ^0.1.3
  geocoding: ^3.0.0
  collection: ^1.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo_playstore.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 600
